repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id:   black
        exclude: migrations
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--skip", "migrations"]
        name: isort (python)
-   repo: https://github.com/pycqa/flake8.git
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: ["flake8-commas", "flake8-quotes"]
