# Generated by Django 4.1.2 on 2023-06-17 15:42

import cards.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_pile', cards.fields.CardsField(default=[])),
                ('discard_pile', cards.fields.CardsField(default=[])),
                ('hand', cards.fields.CardsField(default=[])),
                ('played_cards', cards.fields.CardsField(default=[])),
                ('duration_cards', cards.fields.CardsField(default=[])),
                ('narnia_pile', cards.fields.CardsField(default=[])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decks', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decks', to='players.player')),
            ],
        ),
    ]
