# Generated by Django 4.1.2 on 2023-04-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='narnia_pile',
            field=models.JSONField(default=list),
        ),
    ]
