# Generated by Django 4.1.2 on 2022-12-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='available_money',
            field=models.IntegerField(default=0),
        ),
    ]
