# Generated by Django 4.1.2 on 2023-02-04 16:38

import cards.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('games', '0001_initial'),
        ('turns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current_turn', models.BooleanField(db_index=True, default=True)),
                ('card', cards.fields.CardField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhoc_turns', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhoc_turns', to='players.player')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhoc_turns', to='turns.turn')),
            ],
        ),
    ]
