# Generated by Django 4.1.2 on 2023-01-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0002_turn_available_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='state',
            field=models.CharField(
                choices=[('action', 'Action Phase'), ('buy', 'Buy Phase')],
                default='action',
                max_length=10,
            ),
        ),
    ]
