# Generated by Django 4.1.2 on 2023-02-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('turns', '0002_adhocturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocturn',
            name='target_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='players.player'),
        ),
        migrations.AddField(
            model_name='adhocturn',
            name='turn_order',
            field=models.IntegerField(default=0),
        ),
    ]
