# Generated by Django 4.1.2 on 2023-04-01 14:54

import cards.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('games', '0001_initial'),
        ('turns', '0003_adhocturn_target_player_adhocturn_turn_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current_turn', models.BooleanField(db_index=True, default=True)),
                ('card', cards.fields.CardField(max_length=100)),
                ('turn_order', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queued_turns', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queued_turns', to='players.player')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queued_turns', to='turns.turn')),
            ],
        ),
    ]
