# Generated by Django 4.1.2 on 2023-04-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('turns', '0004_queuedturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedturn',
            name='target_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='players.player'),
        ),
    ]
