# Generated by Django 4.1.2 on 2023-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0005_queuedturn_target_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedturn',
            name='perform_simple_actions',
            field=models.BooleanField(default=False),
        ),
    ]
