# Generated by Django 4.1.2 on 2023-04-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0006_queuedturn_perform_simple_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocturn',
            name='card_form_field_string',
            field=models.CharField(default='adhocturn_form', max_length=250),
        ),
        migrations.AddField(
            model_name='adhocturn',
            name='card_form_title_field_string',
            field=models.CharField(default='adhocturn_action_title', max_length=250),
        ),
        migrations.AddField(
            model_name='queuedturn',
            name='card_form_field_string',
            field=models.CharField(default='adhocturn_form', max_length=250),
        ),
        migrations.AddField(
            model_name='queuedturn',
            name='card_form_title_field_string',
            field=models.CharField(default='adhocturn_action_title', max_length=250),
        ),
    ]
