# Generated by Django 4.1.2 on 2023-01-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kingdom', models.JSONField(default=list)),
                ('trash_pile', models.JSONField(default=list)),
                ('game_hash', models.UUIDField()),
                ('turn_order', models.JSONField(default=list)),
                ('is_over', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(to='players.player')),
            ],
        ),
    ]
