# Generated by Django 4.1.2 on 2022-10-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trash_pile',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='turn_order',
            field=models.JSONField(default=list),
        ),
    ]
